blog/urls.py
from django.urls import path 
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [ 
    path('', views.post_list, name = 'post_list'), 
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name = "post_list"),
    # <> are path converters convert url into variables
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name="post_detail"),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name="post_search" ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')), 
    path('', include('blog.urls')),
    path(
            'sitemap.xml', 
            sitemap, 
            {'sitemaps': sitemaps}, 
            name='django.contrib.sitemaps.views.sitemap'
        )
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import  reverse
from taggit.managers import  TaggableManager


'''CREATING CUSTOM OBJECTS'''
# objects (models.objects)is the default manager for every model that retrieves all objects in the database 
# However, on can define custom managers for the models
# Below is a custom manager that retrieves posts with a status='published'
class PublishedManager(models.Manager):
    def get_queryset(self):
        #Fetch the usual queryset returned by the default objects then add a filter to it 
        return super(PublishedManager, self).get_queryset().filter(status='published')


# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'), ('published', 'Published'),
    )
    title = models.CharField(max_length=200)

    # slug is intended to be used in urls, a slug is a short label containing only letters, numbers...
    # unique_for_date prevents the entry of two records with the same slug and date
    # unique_for_date ensures that there is only one post with a slug for a given date
    # Django prevents multiple posts from having the same slug
    slug = models.SlugField(max_length=250, unique_for_date='publish') # Publish here refers to the publish field

    # Author has a many to one relationship 
    # The field will contain the primary key of the user in the User model 
    # related_name is the name givven to the reverse relationship from User to Post, this enables easy access of related objects
    author = models.ForeignKey(User,  on_delete=models.CASCADE, related_name='blog_posts')

    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True) # auto_now_add, updates with time and date at the creation of the record
    updated = models.DateTimeField(auto_now=True) #  Updates whenever Model.save() is called
    
    # the choices parameter limits us to one of the specified choices
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    # Tags here
    tags = TaggableManager()

    class Meta:
        # This tells django to sort data beginning with the latest published by default 
        ordering = ('-publish',)
    
    def __str__(self):
        # The default human readable representation of the object 
        return self.title

    #Creating custom managers for the post model   
    objects = models.Manager() # Ths is the default manager, accessed via Post.objects
    published = PublishedManager() # Post.published

    # IF no manager is defined in the model, django automaticaly creates the objects default manager

    def get_absolute_url(self):
        '''
        The canonical url, is the single url that is the main url for a blog post
        setting the canonical url here means that we can refer to it from the templates 
        '''
        return reverse('blog:post_detail', args=[ self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug ])


class Comment(models.Model):
    '''
    In the post, atribute below there is a related_name atribute
    the related_name atribute allows you to name the relationship from 
    the related object back to this one. For instance 
    you can retrieve the post of a comment using comment.post
    you can retrieve all comments using post.comments.all() instead of post.comment_set.all()
    '''
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)# Creation date 
    updated = models.DateTimeField(auto_now=True)# updated date everytime there is an update
    active = models.BooleanField(default=True)

    # Tell django that whenever comment objects are called, order using created field
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    
class PostImage(models.Model):
    post  = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="blog_images")
    thumbnail = models.ImageField(upload_to="blog_thumbnails")

blog/forms.py
from django import forms 
from .models import Comment

class EmailPostForm(forms.Form):
    name =  forms.CharField(max_length=25, widget=forms.TextInput(
                attrs={'placeholder': "Name of sender..."}))
    email = forms.EmailField(widget=forms.TextInput(
                attrs={'placeholder': "Sender email..."}))
    to = forms.EmailField(widget=forms.TextInput(
                attrs={'placeholder': "Recepient email..."}))
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.contrib.postgres.search import SearchVector


# Create your views here.
# Views receive web request and return web response 
# Each view renders a template, passing variables to it

def post_detail(request, year, month, day, post):

    # Fetch the post 
    post = get_object_or_404(Post, slug=post, 
                                    status='published', 
                                    publish__year=year, 
                                    publish__month=month, 
                                    publish__day=day)
    
    # Fetch the comments 
    comments  = post.comments.filter(active=True)


    # This is a flag used to display whether there is a new comment so that it can be displayed
    new_comment = None 
    # The detail view also includes a form for users to submit comments, the comment form appears as a modal 
    if request.method == 'POST':
        comment_form = CommentForm(data = request.POST)
        if comment_form.is_valid():
            # Create a new comment object but dont save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the post to the comment  
            new_comment.post = post
            # Now we can save  
            new_comment.save()
    else:
        comment_form = CommentForm()
    
    # THE THREE LINES OF CODE BELOW FUNCTION TO RECCOMEND SIMILAR POSTS TO USERS ON DETAILVIEW
    # Get a python [list] of ids of tags for the current post...
    # values_list() queryset returns tuples with the values of the given fields...
    # flat=True is to get the list [1, 2, 3, ...] instead of [(1,), (2,), (3,) ...] 
    post_tag_ids = post.tags.values_list("id", flat=True)
    # Fetch all posts that have the tags in the post_tag_ids queryset
    similar_posts = Post.published.filter(tags__in=post_tag_ids).exclude(id=post.id)
    # Use Count to generate a value that represents number of shared tags
    # Order the results by the number of shared tags in -descending-order...
    # Order the resulting queryset above by published so that recent posts come first...
    # for more info on annotate check page 127 in django documentation book     
    similar_posts = similar_posts.annotate(same_tags =Count("tags")).order_by('-same_tags', "-publish")[:4]

    return render(request,"blog/post/detail.html",
                # Context
                {
                "post": post, # The blogpost   
                "comments": comments, # The comments under the blog
                "new_comment": new_comment, # The comment just submitted
                "comment_form": comment_form, # The modelForm object
                "similar_posts": similar_posts
                }) 
                
# This handles the form 
def post_share(request, post_id):
    '''
    Takes a post and sends it as an email
    '''
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False 
    if request.method == 'POST':
        # If the request is POST this means the user has submitted data 
        form = EmailPostForm(request.POST) # Create a form object
        if form.is_valid():
            # The form has passed the nescesarry validation
            cd = form.cleaned_data
            # Send the email using the form data 
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} reccomends you read blog post: {post.title}"
            message = f"Read {post.title} at {post_url} \n" \
                        f"{cd['name']}'s commented {cd['comments']}"
            
            '''
            send_mail() function takes several parameters 
            > SUBJECT
            > MESSAGE
            > SENDER
            > LIST OF RECEPIENTS 
            > fail_silently = bool
            '''
            send_mail(subject, message, "bigballs@admin.com", [cd['to'], ])
            sent = True
    else:
        # When the view is initialy loaded, create an instance of form 
        # The instance is used to display the empty form
        
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post':post, 'form':form, 'sent':sent})


def post_list(request, tag_slug=None):
    object_list = Post.published.all() # Here we use our custom object 
    # Alternatively Post.object.filter(status="published")

    tag = None
    if tag_slug:

        # Fetch the tag from the tag database 
        tag = get_object_or_404(Tag, slug=tag_slug)
        # Get only the posts that have the indicated tag 
        object_list = object_list.filter(tags__in=[tag]) 

    # Instantiate paginator class, display three posts on every page
    paginator = Paginator(object_list, 3) 
    # Get the page parameter, which indicates current page number
    page = request.GET.get('page') 
    try:
        # Obtain the objects of the desired page by calling page() method of paginator 
        posts = paginator.page(page)
    except  PageNotAnInteger:
        # If page is not an integer deliver the first page
        # When you  load blog/ this line will be rendered
        posts = paginator.page(1)
    except EmptyPage:
        # If page is oyut of range, deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(
                    request, 
                    'blog/post/list.html', 
                    {'posts':posts,'tag':tag,}
                )

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    # The user has submitted a request for the resource
    if "query" in request.GET:
        form =  SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query'] # Query is the form field, get its content
            # For more options on search including adding weight to search terms, ordering and word-stem,
            # View django3 by example page 88
            results = Post.published.annotate(search=SearchVector('title','body'),).filter(search=query)
        
    return render(request, 'blog/post/search.html',{'form':form,'query':query,'results':results})


# from django.views.generic import ListView
# class PostListView(ListView):

#     # Default: model = Post
#     queryset = Post.published.all()
#     # Default: post_list
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}

    <div class="blog-post">
        <h2>{{ post.title }}</h2>
        <span class="post_info">Published {{ post.publish }} by {{ post.author }}</span>
        {% for image in post.postimage_set.all %}
                    <img 
                        src="{{ image.image.url }}" 
                        alt="thumbnail" 
                        class="mr-1"
                    /> 
        {% endfor %}
        <p>
            {{ post.body|markdown }}
        </p>
        <p>
            <a href="{% url 'blog:post_share' post.id %}" class="blog-button">Share this post</a>
        </p>
    </div>

    {% comment %} the list of comments for each article {% endcomment %}
    <div class="comment-list">
        <h2>
            Comments
        </h2>
        <button class="blog-button" id="open">Add a comment</button>
        {% for comment in comments %}
            <div class="comment">
                <span class="post_info">
                    Comment {{ forloop.counter }} | by {{ comment.name }} | on {{ comment.created }}
                </span>
                <p>
                    {{ comment.body|linebreaks }}
                </p>  
            </div>
        {% empty %}
            <div class="comment">
                <p>There are no comments yet</p>
            </div>
        {% endfor %}
    </div>

    {% comment %} the form to display the comments  {% endcomment %}
    <div class="modal" id="modal">
        <div class = "modal-backdrop"></div>
        <div class="modal-body">
            <button class="modal-close" id="close">close</button>
            <div class="form-tile">
                {% if new_comment %}
                    <h2>Your comment has been posted</h2>
                {% else %}
                    <h2>Add a new comment</h2>
                    <form method="post">
                        {{ comment_form.as_p }}
                        {% csrf_token %}
                        <input type="submit" value= "Add Comment"/>
                    </form>
                {% endif %}
            </div> 
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script type="text/javascript">
        var open = document.getElementById("open");
        var close = document.getElementById("close")
        var modal = document.getElementById("modal")

        open.addEventListener("click", function(event){
            event.preventDefault(); 
            modal.style.display = 'block';
        })

        close.addEventListener("click", function(event){
            event.preventDefault();
            modal.style.display = 'none';
        })
    </script>
{% endblock javascript %}

{% block sidebar %}
    <h3>Similar posts</h3>
    {% for post in similar_posts %}
        <a href="{{ post.get_absolute_url }}" class="sidebar-link">
            {{ post.title }}
        </a>
    {% endfor %}
{% endblock sidebar %}

blog/templates/blog/post/latest_posts.html
<h3>Latest Posts</h3>
{% for post in latest_posts %}
    <a href="{{ post.get_absolute_url }}" class="sidebar-link">
        {{ post.title }}
    </a> 
{% endfor %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}


{% block title %}
My blogogio
{% endblock title %}

{% block content %}

    {% if tag %}
        <h2>These are the posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <div class="posts">

            {% comment %} title  {% endcomment %}
            <h2><a href="{{ post.get_absolute_url }}" class="post-title">{{ post.title }}</a></h2>

            {% comment %} article info {% endcomment %}
            <span class="post_info">Published: {{ post.publish }} by {{ post.author }}</span>

            {% comment %} displaying the tags {% endcomment %}
            <div class="tag-div">
                {% for tag in post.tags.all %}
                    <a class="tags" href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                {% endfor %}
            </div>

            {% comment %} truncatewords_html truncates a string avoiding unclosed html tags  {% endcomment %}
            <div class="post_body">
                {% for image in post.postimage_set.all %}
                    <img 
                        src="{{ image.thumbnail.url }}" 
                        alt="thumbnail" 
                        class="mr-1"
                    /> 
                {% endfor %}
                <div class="post_body_p">
                    <p> {{ post.body|markdown|truncatewords_html:30 }}</p> 
                </div>
            </div>

        </div>
    {% endfor %}
    {% comment %} 
        Pagination template expects a page object in order to display current page 
        and total pages, the page object passed to pagination template is called posts 
        {% include "pagination.html" with page=posts %}    function view
        {% include "pagination.html" with page=page_obj %} class view
    {% endcomment %}
    {% include "pagination.html" with page=posts %}

{% endblock content %} 

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} Search {% endblock title %}

{% block content %}
    {% if query %}
        <h1>Posts containing: {{ query }}</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} results{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <div class="posts">
                <h2><a href="{{ post.get_absolute_url }}" class="post-title">{{ post.title }}</a></h2>
                <span class="post_info">Published: {{ post.publish }} by {{ post.author }}</span>
                <p> {{ post.body|markdown|truncatewords_html:30 }}</p>
            </div>
        {% empty %}
            <p>There are no results for your querry</p>
        {% endfor %}
        <div class="search-again">
            <a href={% url 'blog:post_search' %}>Search Again</a>
        </div>
    {% else %}
        {% comment %} if querry is empty present the form to the user {% endcomment %}
        <div class="form-tile form">
            <h2>Search for posts</h2>
            <form method="get">
            {% comment %} because the method is get, the form's fields will be shown 
            in the url for instance if someone searches for "book"
            url will include /?query=book {% endcomment %}
                {{form.as_p}}
                <input type="submit" value="Search"/>
            </form>
        </div>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}


{% block title  %}
    Share post
{% endblock title  %}

{% block content %} 
    {% if sent %}
    <div class="form-tile">
        <h1>Email successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    </div>
    {% else %}
        <div class="form-tile form">
            <h2>Share: <small class="form-small">{{ post.title }} by e-mail</small></h1>
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value= "Send e-mail"/> 
            </form>
        </div>
    {% endif %}
{% endblock content %}